account_id = "f03ac6f7f9be6238eabb9d9d2097cec8"
name = "<APP-NAME>-dev"
type = "webpack"
zone_id = "c8bf4d84a7912cd966204bb83946d7fd"
workers_dev = true
compatibility_date = "2022-03-16"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.staging]
name = "<APP-NAME>-staging"
workers_dev = false
route = "https://<APP-NAME>-staging.alemoretto.it/*"

[env.production]
name = "<APP-NAME>"
workers_dev = false
route = "https://<APP-NAME>.alemoretto.it/*"

